[package]
name = "docsort"
version = "0.1.0"
edition = "2024"
description = "DocSort automatically classifies documents after user login."
license = "MIT"
repository = "https://github.com/mttpla/docsort"
homepage = "https://github.com/mttpla/docsort"

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.8"
confy = "0.6"
log = "0.4"
flexi_logger = "0.31"
thiserror = "1"
single-instance = "0.3"
clap = { version = "4.5", features = ["derive"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.52"
